# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "samcrudstack"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "samcrudstack"
region = "ap-southeast-2"
disable_rollback = true
parameter_overrides = "AppName=\"samcrudstack\" ClientDomains=\"http://localhost:8080\" AdminEmail=\"jonathan@caffeineinteractive.com\" AddGroupsToScopes=\"true\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[staging.deploy.parameters]
stack_name = "samcrudstack"
resolve_s3 = true
s3_prefix = "samcrudstack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "AppName=\"samcrudstack\" ClientDomains=\"http://localhost:8080\" AdminEmail=\"jonathan@caffeineinteractive.com\" AddGroupsToScopes=\"true\""
image_repositories = []

[local.deploy.parameters]
stack_name = "samcrudstack"
resolve_s3 = true
s3_prefix = "samcrudstack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "AppName=\"samcrudstack\" ClientDomains=\"http://localhost:8080\" AdminEmail=\"jonathan@caffeineinteractive.com\" AddGroupsToScopes=\"true\""
image_repositories = []
